export const feature = [
    {
      id: '1',
      img: '/Featured/cap3.jpg',
      name: "Weaving Cap",
      rate: "2.0",
      price: 10.99,
      category: "Accessories",
      description: "A beautifully crafted weaving cap, perfect for any occasion.",
      quantity: 0,
    },
    {
      id: '2',
      img: '/Featured/bag4.jpg',
      name: "Black School Bag",
      rate: "2.0",
      price: 25.99,
      category: "Bags",
      description: "A sturdy and stylish school bag with ample space.",
      quantity: 0,
    },
    {
      id: '3',
      img: '/Featured/cap.jpg',
      name: "Latest Face Cap",
      rate: "5.0",
      price: 15.99,
      category: "Accessories",
      description: "A trendy face cap to complement your style.",
      quantity: 0,
    },
    {
      id: '4',
      img: '/Featured/shoe3.jpg',
      name: "Traditional Cap",
      rate: "4.0",
      price: 12.99,
      category: "Accessories",
      description: "A cap that reflects tradition and elegance.",
      quantity: 0,
    },
    {
      id: '5',
      img: '/Featured/cap5.jpg',
      name: "Crochet Cap",
      rate: "3.5",
      price: 8.99,
      category: "Accessories",
      description: "Handmade crochet cap, warm and comfortable.",
      quantity: 0,
    },
    {
      id: '6',
      img: '/Featured/cream.jpg',
      name: "High Quality Cream",
      rate: "5.0",
      price: 18.99,
      category: "Skincare",
      description: "A high-quality cream to nourish and protect your skin.",
      quantity: 0,
    },
    {
      id: '7',
      img: '/Featured/shoe.jpg',
      name: "Brown Sandal",
      rate: "2.0",
      price: 22.99,
      category: "Footwear",
      description: "Comfortable brown sandals, perfect for casual outings.",
      quantity: 0,
    },
    {
      id: '8',
      img: '/Featured/shoe2.jpg',
      name: "Black Shoe",
      rate: "4.0",
      price: 45.99,
      category: "Footwear",
      description: "Elegant black shoes suitable for formal events.",
      quantity: 0,
    },
    {
      id: '9',
      img: '/Featured/shoe3.jpg',
      name: "White Sneakers",
      rate: "3.0",
      price: 30.99,
      category: "Footwear",
      description: "Stylish white sneakers for a modern look.",
      quantity: 0,
    },
    {
      id: '10',
      img: '/Featured/slipper.jpg',
      name: "White Slippers",
      rate: "2.0",
      price: 12.99,
      category: "Footwear",
      description: "Comfortable white slippers for everyday wear.",
      quantity: 0,
    },
  ];
  
  export const fresh = [
    {
      id: '1',
      img: './Featured/bag1.jpg',
      name: "Casual Backpack",
      category: "Bags",
      description: "A casual backpack, perfect for everyday use.",
      price: 19.99,
      rate: "4.0",
      quantity: 0,
    },
    {
      id: '2',
      img: './Featured/bag2.jpg',
      name: "Fashion Tote Bag",
      category: "Bags",
      description: "A stylish tote bag for all your essentials.",
      price: 29.99,
      rate: "4.5",
      quantity: 0,
    },
    {
      id: '3',
      img: './Featured/bag3.jpg',
      name: "Leather Handbag",
      category: "Bags",
      description: "Elegant leather handbag for a sophisticated look.",
      price: 39.99,
      rate: "5.0",
      quantity: 0,
    },
    {
      id: '4',
      img: './Featured/cap1.jpg',
      name: "Sports Cap",
      category: "Accessories",
      description: "A sporty cap to keep you cool during workouts.",
      price: 12.99,
      rate: "4.0",
      quantity: 0,
    },
    {
      id: '6',
      img: './Featured/cap3.jpg',
      name: "Weaving Cap",
      category: "Accessories",
      description: "A beautifully crafted weaving cap, perfect for any occasion.",
      price: 10.99,
      rate: "2.0",
      quantity: 0,
    },
  ];
  