export const feature = [
    {
        id: '1',
        img: '/Featured/cap3.jpg',
        name: "Weaving Cap",
        rate: "2.0",
        price: `$10.99`,
        category: "Accessories",
        description: "A beautifully crafted weaving cap, perfect for any occasion.",
    },
    {
        id: '2',
        img: '/Featured/bag4.jpg',
        name: "Black School Bag",
        rate: "2.0",
        price: 25.99,
        category: "Bags",
        description: "A sturdy and stylish school bag with ample space.",
    },
    {
        id: '3',
        img: '/Featured/cap.jpg',
        name: "Latest Face Cap",
        rate: "5.0",
        price: 15.99,
        category: "Accessories",
        description: "A trendy face cap to complement your style.",
    },
    {
        id: '4',
        img: '/Featured/shoe3.jpg',
        name: "Traditional Cap",
        rate: "4.0",
        price: 12.99,
        category: "Accessories",
        description: "A cap that reflects tradition and elegance.",
    },
    {
        id: '5',
        img: '/Featured/cap5.jpg',
        name: "Crochet Cap",
        rate: "3.5",
        price: 8.99,
        category: "Accessories",
        description: "Handmade crochet cap, warm and comfortable.",
    },
    {
        id: '6',
        img: '/Featured/cream.jpg',
        name: "High Quality Cream",
        rate: "5.0",
        price: 18.99,
        category: "Skincare",
        description: "A high-quality cream to nourish and protect your skin.",
    },
    {
        id: '7',
        img: '/Featured/shoe.jpg',
        name: "Brown Sandal",
        rate: "2.0",
        price: 22.99,
        category: "Footwear",
        description: "Comfortable brown sandals, perfect for casual outings.",
    },
    {
        id: '8',
        img: '/Featured/shoe2.jpg',
        name: "Black Shoe",
        rate: "4.0",
        price: 45.99,
        category: "Footwear",
        description: "Elegant black shoes suitable for formal events.",
    },
    {
        id: '9',
        img: '/Featured/shoe3.jpg',
        name: "White Sneakers",
        rate: "3.0",
        price: 30.99,
        category: "Footwear",
        description: "Stylish white sneakers for a modern look.",
    },
    {
        id: '10',
        img: '/Featured/slipper.jpg',
        name: "White Slippers",
        rate: "2.0",
        price: 12.99,
        category: "Footwear",
        description: "Comfortable white slippers for everyday wear.",
    },
];


export const fresh = [

    {id:'1', img: './Featured/bag1.jpg', name: ""},
    {id:'2', img: './Featured/bag2.jpg', name: ""},
    {id:'3', img: './Featured/bag3.jpg', name: ""},
    {id:'4', img: './Featured/cap1.jpg', name: ""},
    {id:'6', img: './Featured/cap3.jpg', name: ""},
    // {id:'7', img: './Featured/shoe4.jpg', name: ""},

]


// {id:'14', img: './Featured/shoe1.jpg', name: ""},
// {id:'17', img: './Featured/shoe4.jpg', name: ""},
// {id:'18', img: './Featured/shoe5.jpg', name: ""},
// {id:'20', img: './Featured/slipper1.jpg', name: ""},
